In [2]:
import numpy as np
import random
from collections import namedtuple
from scipy.stats import entropy

In [7]:
l = []
m = [0,1]
m = l.copy()
print(m)

l = np.array([(1,2), (1,3), (2,1), (1,2)])
print(np.unique(l, axis=0))

[]
[[1 2]
 [1 3]
 [2 1]]


In [5]:
mi_T = [random.randint(0, 2-1) for _ in range(25)]
print(f'mi_T = {mi_T}')

l = [0,1,2,3,4]
print(np.mean(l))

l = []
if l:
    print('l is not empty')
else:
    print('l is empty')

i = 5
for i in range(3):
    print(i)
print(i)

mi_T = [1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1]
2.0
l is empty
0
1
2
2


In [12]:
x = np.zeros((5,2))
print(x)
x[0] = [0,1]
print(x)
d = [0]*10
print(entropy([1./len(d)] * len(d)))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
2.3025850929940455


In [2]:
s = {(0, i) for i in range(25)}
print(s)

{(0, 2), (0, 5), (0, 8), (0, 14), (0, 11), (0, 17), (0, 23), (0, 20), (0, 1), (0, 7), (0, 4), (0, 10), (0, 16), (0, 13), (0, 19), (0, 22), (0, 0), (0, 3), (0, 9), (0, 6), (0, 12), (0, 15), (0, 21), (0, 18), (0, 24)}


In [ ]:
l = np.array([i for i in range(10)])
print(np.where(l % 2 == 0))
idx = np.where(l == 0)[0]
print(idx)

(array([0, 2, 4, 6, 8]),)


IndexError: tuple index out of range